### ISSUE TITLE
Is this project still being actively maintained?

### ISSUE THREAD

**Issue by kaicataldo** [not-an-aardvark/eslint-rule-composer#11]
Hey @not-an-aardvark! Is this project still being actively maintained? It's such a great idea, and I think some additional APIs could go a long way in making it even more useful.

If you don't currently have the bandwidth, I'm considering publishing an alternative package that I would maintain, since we're doing some work in Babel's ESLint integration that could benefit from it. Wanted to check in here first so we're not duplicating work.

Thanks, and hope you're doing well!

**Comment by not-an-aardvark** [comment]
Hi, hope you're doing well. I'm not really maintaining this project at the moment -- feel free to fork it/publish an alternative.

**Comment by kaicataldo** [comment]
Thanks!
